name: Create release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag semver (e.g., 0.1.0)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create and push tag
        run: |
          git fetch origin
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          mode: "COMMIT"
          configurationJson: |
            {
              "fetchViaCommits": true,
              "template": "#{{CHANGELOG}}",
              "categories": [
              {
                "title": "## 🚀 Features",
                "labels": ["feat"]
              },
              {
                "title": "## ⚙️ Fixes",
                "labels": ["fix"]
              },
              {
                "title": "## Other",
                "labels": []
              }
              ],
              "label_extractor": [
              {
                "pattern": "^(build|ci|chore|doc|docs|wiki|remove|deprecate|security|dependency|package|feat|feature|fix|bug|perf|optimize|refactor|revert|style|test):(.*)",
                "target": "$1"
              },
              {
                "pattern": "^(build|ci|chore|doc|docs|wiki|remove|deprecate|security|dependency|package|feat|feature|fix|bug|perf|optimize|refactor|revert|style|test){1}(\\([\\w\\-\\.]+\\))?(!)?:(.*)",
                "target": "$1"
              }
              ],
              "pr_template": "- [#{{CLEAN_TITLE}}](https://github.com/#{{OWNER}}/#{{REPO}}/commit/#{{MERGE_SHA}}) #{{TICKET}}",
              "custom_placeholders": [
              {
                "name": "CLEAN_TITLE",
                "source": "TITLE",
                "transformer": {
                "pattern": "\\s*\\[?FRVR-[A-Za-z0-9]+\\]?\\s*",
                "method": "replaceAll",
                "target": " "
                }
              },
              {
                "name": "TICKET",
                "source": "TITLE",
                "transformer": {
                "pattern": "\\[?FRVR-([A-Za-z0-9]+)\\]?",
                "method": "regexr",
                "target": "[FRVR-$1](https://linear.app/frvr/issue/FRVR-$1)"
                }
              }
              ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log changelog
        run: echo "${{steps.changelog.outputs.changelog}}"

      - name: Create release
        uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
        with:
          tag_name: ${{ github.event.inputs.version }}
          body: ${{steps.changelog.outputs.changelog}}