name: Create release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag semver (e.g., 0.1.0)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create and push tag
        run: |
          git fetch origin
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          mode: "HYBRID"
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}",
              "categories": [
                {
                    "title": "## 🚀 Features",
                    "labels": ["feat"]
                },
                {
                    "title": "## ⚙️ Fixes",
                    "labels": ["fix"]
                },
                {
                    "title": "## Other",
                    "labels": []
                }
              ],
              "label_extractor": [
                {
                  "pattern": "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\\([\\w\\-\\.]+\\))?(!)?: ([\\w ])+([\\s\\S]*)",
                  "target": "$1"
                }
              ],
              "pr_template": "- #{{TITLE}} - #{{URL}} #{{TICKET}}",
              "custom_placeholders": [
                {
                  "name": "TICKET",
                  "source": "TITLE",
                  "transformer": {
                    "pattern": "\\[FRVR-([A-Za-z0-9]+)\\]",
                    "method": "regexr",
                    "target": "- ([Linear FRVR-$1](https://linear.app/frvr/issue/FRVR-$1))"
                  }
                }
              ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log changelog
        run: echo "${{steps.changelog.outputs.changelog}}"

      - name: Create release
        uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
        with:
          tag_name: ${{ github.event.inputs.version }}
          body: ${{steps.changelog.outputs.changelog}}